version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3005:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "6220:6220"
    environment:
      - DATABASE_URL=postgresql://plane:plane@host.docker.internal:5434/vj
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always


